### PR TITLE
Muting and removing unused variables

### PR DESCRIPTION
**Pull request by FredericGuilbault**
eslint was complaining about unused vars when bundling

### CODE REVIEW

**Comment by tkurki** [comment]
For some reason you are issuing pull requests to my fork of the real repo, https://github.com/vokkim/tuktuk-chart-plotter. Please direct pull requests there, even if I merge your PR here it won't make it to the upstream original repo.

**Comment by FredericGuilbault** [comment]
Vokkim haven't accepted your pull request of this branch yet. 
Therefor the concerned code is not part of vokkim/tuktuk-chart-plotter. 

Sending a new PR to the original repo. With a new branch name, but all the same commits would be considered spamming. 

At this point. You are defacto the maintainer of this feature cuz you are the only one who have this branch on his repository ( exept me that have tricked github by adding git upstream and branch it on a new name). 

That's why I have send the commit to you.

**Comment by tkurki** [comment]
Oh ok it was intentional, did not realiase that. The branch is very much work in progress, it may change quite a bit, PRs probably aren’t the very useful.

**Comment by tkurki** [comment]
Rendertracks signature is now wrong and will cause errors once I get around to using units and will cause errors once I get around to using the parameters.

**Comment by FredericGuilbault** [comment]
Humm, the problem occured to me when I merged it into vokkim's HEAD  and it's not the only one I had so it might have caused new problems I didin't saw amongs the other ones. ...My bad. 

The PR you made on vokkim repo made me think this was a tracking feature ready to be merged. But if you tell me it's a WIP, ill wait before trying to merge your code (both for my personal use && for solving merging conflict to help the feature to be adopted by tuktuk maintainer ). So I deleted my upstream (witch is your branch) as this PR is effectively not good and we aren't there yet. 

But I must say, Im using the tracking a lot on navionics, so im looking foward for it tuktuk :D

**Pull request closed without merging**
